### ISSUE TITLE
Compare two commits

### ISSUE THREAD

**Issue by nomeata** [phadej/github#109]
Hi,

it seems that this API endpoint is not supported yet:
https://developer.github.com/v3/repos/commits/#compare-two-commits

Greetings,
Joachim

**Comment by jwiegley** [comment]
@nomeata I think this project hasn't seen much maintenance, and I don't need it for my job anymore, so I'm not sure when new APIs will get added.  If you'd like to take over maintainership, I'd be happy to give you control of the repository!

**Comment by nomeata** [comment]
So far, I needed this for a small toy project (a tool that tells me what of my github forks are fully merged and can be deleted), so I’ll pass for now :-)

**Comment by phadej** [comment]
@nomeata it actually is, http://hackage.haskell.org/package/github-0.13.2/docs/Github-Repos-Commits.html#v:diff

In next release the discoverability of endpoints will be a bit better.

**Comment by nomeata** [comment]
Thanks. If I now could only remember what I wanted to do with this :-)

**Comment by nomeata** [comment]
Hmm. It seems that without the primed version (which allows authenticated requests), this is not yet useful to me :-(. Can you re-open this (It seems I cannot)?

**Comment by nomeata** [comment]
Also, this has been added (b158582), but not yet released to hackage, it seems.

**Comment by phadej** [comment]
Now there is http://hackage.haskell.org/package/github-0.14.0/candidate with fixes

**Comment by phadej** [comment]
`0.14.0` released. Please check if it works for you.
