### ISSUE TITLE
Decouple request creation from execution

### ISSUE THREAD

**Issue by phadej** [phadej/github#127]
After working with this API, and making few others, I found that separating request creation and execution is better (i.e. more flexible) design.

Now one cannot use different network client or add new endpoints.

Shorly

```hs
-- New stuff:
data GithubRequest a = GithubRequestGet Url
                     | ...

-- or alternatively
data GithubRequest a where
  GithubRequestGet :: Url -> GithubRequest a
  GithubRequestMultiGet :: Url -> GithubRequest [a]

execGithubRequest :: FromJSON a => GithubRequest a -> IO (Either Error a)
execGithubRequest' :: FromJSON a => Maybe GithubAuth -> GithubRequest a -> IO (Either Error a)

publicOrganizationForRequest :: String -> GithubRequest [SimpleOrganisation]
publicOrganizationForRequest org = GithubRequestGet ...

-- Old IO methods become:
publicOrganizationsFor :: String -> IO (Either Error [SimpleOrganization])
publicOrganizationsFor = execGithubRequest . publicOrganizationForRequest

publicOrganizationsFor' :: Maybe GithubAuth -> String -> IO (Either Error [SimpleOrganization])
publicOrganizationsFor' auth = execGithubRequest' auth . publicOrganizationForRequest
```

How does this sound? I can make a refactoring, it's quite straight-forward.

**Comment by phadej** [comment]
The idea implemented in bindings to other api:
- The request type: https://github.com/futurice/haskell-planmill-client/blob/a961d7f50f87d613ab40c15bf9d6d20768555f56/src/PlanMill/Types/Request.hs#L41
- and one way to execute it https://github.com/futurice/haskell-planmill-client/blob/a961d7f50f87d613ab40c15bf9d6d20768555f56/src/PlanMill/Operational.hs#L86

**Comment by jwiegley** [comment]
I like this idea very much.
