### ISSUE TITLE
Listing own starred repos is broken in 0.13.2

### ISSUE THREAD

**Issue by aristidb** [phadej/github#173]
I suspect it may be fixed already in master, as I saw a commit message saying "Fixed watch and star", so maybe it would already be enough to just make a new release?

The JsonError looks like this:

```
failed to parse field homepage: expected String, encountered Null on the JSON: Array [Object (fromList [("homepage",Null),("hooks_url",String "https://api.github.com/repos/...
```

**Comment by aristidb** [comment]
I can confirm that using master fixes the issue.

**Comment by phadej** [comment]
@aristidb I plan to make `0.14.0` this week. Please tell, if `master` works for you otherwise, that's a valuable information for me.

**Comment by aristidb** [comment]
I updated master, and it still works with my (tiny) project.

**Comment by phadej** [comment]
@aristidb I'll try to cut the release today, latest tomorrow.

**Comment by phadej** [comment]
[`github-0.14.0`](http://hackage.haskell.org/package/github-0.14.0) released
