### ISSUE TITLE
Commit date

### ISSUE THREAD

**Issue by 2016rshah** [phadej/github#197]
If I'm not mistaken, the [Github API endpoint](https://developer.github.com/v3/repos/commits/#get-a-single-commit) for commits provides the date/time the commit was created. Would it be feasible to add that attribute to the [`Commit` type](https://hackage.haskell.org/package/github-0.14.1/docs/GitHub-Data-GitData.html#t:Commit) or the [`GitCommit` type](https://hackage.haskell.org/package/github-0.14.1/docs/GitHub-Data-GitData.html#t:GitCommit)? Ideally I would like to compare multiple commits to see which is the most recent.

**Comment by phadej** [comment]
There are `date` fields on `author` and `committer` (when created and committed respectively), and that field is in [`GitUser`](https://hackage.haskell.org/package/github-0.14.1/docs/GitHub-Data-GitData.html#t:GitUser).

I cannot see other date/times. Correct me if I'm wrong

**Comment by 2016rshah** [comment]
That is exactly what I was looking for, thank you!
