### ISSUE TITLE
starred_at

### ISSUE THREAD

**Issue by nakaji-dayo** [phadej/github#198]
Can I get the `starred_at` in `GitHub.Endpoints.Activity.Starring#myStarred` ?
https://developer.github.com/v3/activity/starring/#list-repositories-being-starred

If it can not, I want to commit to add this feature.

The API response will change by `Accept` header.
I want you to tell me if there are any other endpoints that would be helpful.

**Comment by phadej** [comment]
You'll need to change [`Request`](http://hackage.haskell.org/package/github-0.14.1/docs/GitHub-Data-Request.html#t:Request) data. I'm happy to review the PR

**Comment by nakaji-dayo** [comment]
Thank you for your reply!
I sent the PR.
