### ISSUE TITLE
pagination support

### ISSUE THREAD

**Issue by joeyh** [phadej/github#2]
Only 30 items max are returned by any query. This is quite bad for github-backup, which wants *every* item.

The github api has a pagination interface. See http://developer.github.com/v3/#pagination

**Comment by phadej** [comment]
I'm not sure which parts of this issue are implemented/fixed. AFAICS the pagination support is there, and soon the plugging your own stuff will be via https://github.com/phadej/github/issues/127.

Please open new issues, if I'm missing something.
