### ISSUE TITLE
ParseError for pullRequestsForR when specifying "all" or "closed"

### ISSUE THREAD

**Issue by filib** [phadej/github#205]
Pretty much as the title says. I'll do a bit more investigation to see if I can get a more meaningful insight into exactly which field is causing the issue.

```
ParseError "when expecting a Text, encountered Null instead"
```

**Comment by phadej** [comment]
compile with `aeson >= 0.11`, it will print the key then

**Comment by filib** [comment]
Cheers, I'll give that a shot.

**Comment by filib** [comment]
@phadej I don't get a parse error at all with `aeson-0.11.0.0`. Feel free to close if you think it's the best option. Thanks for such a quick reply.

**Comment by phadej** [comment]
Hmm, could you try with `aeson-0.10`, is it because of it?

**Comment by filib** [comment]
I think your _hmm_ there was warranted. I seem to have made a mistake, it is still failing with `aeson-0.11.0.0.`

```
Error in $[14].body: failed to parse field body: expected Text, encountered Null"
```

I decided to use `curl` to see if there was anything obvious.

```
curl -i 'https://api.github.com/repos/thoughtbot/paperclip/pulls?per_page=100&state=closed' > test.json
```

I saved the results here https://gist.github.com/filib/d42aea2fa194fcb27966f756c67d6ea6 but I couldn't find any fields called `body` that were `null`. Any ideas?

**Comment by phadej** [comment]
The failing result is probably not on the first page. Let me see

**Comment by phadej** [comment]
I was able to reproduce (got the same `Error in $[14].body`). Now it's fixed.

**Comment by filib** [comment]
Why does this kind of thing happen? Is it because the Github API schema isn't always correct or is it because there is a bug in their API?

**Comment by filib** [comment]
Also, thank-you, your responses were very quick.

**Comment by phadej** [comment]
There are no schema, API is specified by example, so we have to learn details empirically :(

**Comment by filib** [comment]
That must be incredibly frustrating - my sympathies :(
