### ISSUE TITLE
Preferred way of adding new query paramters

### ISSUE THREAD

**Issue by filib** [phadej/github#206]
I'd like to supply additional query parameters to `pullRequestsForR` and wondered if you'd be willing to accept a patch permitting this?

What is your preferred means of adding additional query parameters? I notice that `state` is already supported by passing an additional argument to `pullRequestsForR` but worry that adding more might result in a more cumbersome interface.

Appreciate any suggestions/guidance. Cheers!

**Comment by phadej** [comment]
I'd probably make a single `data ListPullRequestsParams` (better name is welcome) and expose setters (but not constructor), so 

```hs
-- | List pull requests.
-- See <https://developer.github.com/v3/pulls/#list-pull-requests>
pullRequestsForR :: Name Owner -> Name Repo
                 -> ListPullRequestParams
                 -> Maybe Count
                 -> Request k (Vector SimplePullRequest)

defaultListPullRequestParams :: ListPullRequestParams
defaultListPullRequestParams = ...

-- Usage

main :: IO ()
main = executeRequest' request >>= print
  where
    request = pullRequestsForR "phadej" "github" params Nothing
    params  = defaultListPullRequestParams
        & setLprpState All
        & setLprpHead "master"

-- And maybe lens usage too:

main :: IO ()
main = executeRequest' request >>= print
  where
    request = pullRequestsForR "phadej" "github" params Nothing
    params  = defaultListPullRequestParams
        & lprpState .~ All
        & lprpHead  .~ "master"
```

**Comment by phadej** [comment]
(`State` could be real enumeration)

**Comment by phadej** [comment]
This is implemented for pull requests, it will serve as example for now.
