### ISSUE TITLE
Commits endpoint does not take count

### ISSUE THREAD

**Issue by sid-kap** [phadej/github#220]
At http://haddock.stackage.org/lts-5.17/github-0.14.1/GitHub-Endpoints-Repos-Commits.html, it seems like `commitsForR` takes a count, which presumably means the number of commits you want to receive.
However, when pass `Just 1` as the count parameter, I get a long list of commits.

It seems like the Github API no longer allows you to specify the count, according to https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository. (There is no count parameter listed under this function.)

Should we, then, remove the `commitsForR` function?

**Comment by phadej** [comment]
IIRC comimits endpoint is paged. Default executor will do only as many requests as needed to get `count` elements, yet return all fetched. With `Just 1` all elements from the first page are still returned

**Comment by sid-kap** [comment]
Okay, I see. Thanks for the clarifcation.

I think we should document this behavior somewhere. Maybe we should change the name of `Count` to `MaxCount` or `Limit`? Or maybe add a Haddock note under the `Count` type alias to say that this is a limit, not the exact amount. The most verbose/time-consuming option would be to put a Haddock comment next to _every_ function that takes a `Count` argument. Do any of these sound like a good idea?

**Comment by phadej** [comment]
I'll change the parameter from `Maybe Count = Maybe Int` to use new 
```hs
data FetchCount = FetchAll | FetchAtLeast Word`
```

It will self-document better, won't it?

**Comment by sid-kap** [comment]
That sounds excellent! Thanks for taking my suggestion seriously.

**Comment by sid-kap** [comment]
I think a short Haddock comment under the data declaration, explaining why it fetches _at least x_ instead of exactly _x_ (due to paging) would also be good.
