### ISSUE TITLE
Compatibility with http-client-0.5.*

### ISSUE THREAD

**Issue by Daniel-Diaz** [phadej/github#235]
Is it possible to have github upgraded so that it compiles against the newer versions of http-client? I tried a quick fix, but it turned out it wasn't that quick. Some actual code needs change. Like `checkResponse` (former `checkStatus`) does not expect a `CookieJar` anymore. I haven't examined in more detail yet.

Thanks!

**Comment by phadej** [comment]
I'm on this.

**Comment by Daniel-Diaz** [comment]
Thanks!
