### ISSUE TITLE
Release 0.15.0

### ISSUE THREAD

**Issue by phadej** [phadej/github#244]
There aren't any blockers for the release, so if there are people willing to test current master, the help is appreciated.

I'll do some own testing, but plan to release 0.15 on 20.9, i.e. in about a week.

**Comment by simonyangme** [comment]
Is there anything you need help with on pushing out this release?

**Comment by phadej** [comment]
There is a bit hassle at the dayjob, but I should have time to wrap the release next week

**Comment by phadej** [comment]
Released
