### ISSUE TITLE
Add "assignees" to PRs and issues.

### ISSUE THREAD

**Issue by iphydf** [phadej/github#248]
GitHub now supports multiple assignees. We would like to use that information to display it in our [pull-status](https://github.com/iphydf/pull-status) output.

**Comment by phadej** [comment]
pr welcome, fill free to change the `assignee` field to be a `assignees` vector

**Comment by phadej** [comment]
... https://developer.github.com/v3/issues/#get-a-single-issue doesn't mention multiple assignees field yet though. Is it an error in GitHub docs?

**Comment by iphydf** [comment]
Yes, it's outdated. The `mergeable_status` field is also undocumented. Try:
```
curl https://api.github.com/repos/TokTok/toxcore/pulls/131
```

**Comment by iphydf** [comment]
`assignee` is still there by the way, just `assignees` was added. I don't know whether the concept of a "main assignee" exists or is useful. It looks like it's just the alphabetically first one, so perhaps it makes sense to remove the `assignee` field in favour of `assignees`.

**Comment by GrayHatter** [comment]
Assignee is who ever was first assigned, this could be the primary reviwer, or something important to some people. so I've decided to leave it.

**Comment by phadej** [comment]
That field is quite confusing. Or if you really want to leave it, give it a better name, e.g. `issueFirstAssignee`
