### ISSUE TITLE
As an employee at a company that as a GitHub Enterprise instance, I want to be able to specify the URL to the API endpoint

### ISSUE THREAD

**Issue by iand675** [phadej/github#25]
I know it's not your priority, but it would be nice to have.

**Comment by jwiegley** [comment]
Some some support for this was just merged in, can someone check if it addresses this ticket?

**Comment by phadej** [comment]
It should work with http://hackage.haskell.org/package/github-0.14.0/candidate (and 0.13.2 already IIRC)
