### ISSUE TITLE
ParseError "when expecting a MergeableState, encountered String instead"

### ISSUE THREAD

**Issue by iphydf** [phadej/github#269]
As of a few weeks ago, I can no longer get pull requests, e.g. [this one](https://api.github.com/repos/TokTok/apidsl/pulls/18). It errors with the message above. I'm using `pullRequestR`.

**Comment by taktoa** [comment]
I've identified the problem: after `github` makes the API call, it returns an object with `"mergeable_state": "blocked"` which the parser cannot handle.

To fix the problem, we can simply upgrade [the parser](https://github.com/phadej/github/blob/master/src/GitHub/Data/Options.hs#L93-L112) to handle this additional case.

In the future, to make these kinds of issues easier to debug, perhaps the `Data.Aeson.FromJSON.parseJSON` implementations in `github` should use something other than `typeMismatch`; in particular, something that would include the JSON that caused the failure in the error message would greatly aid debugging (I used `fail ("DEBUG: " ++ show v)`, but I'm sure there's another more elegant solution). Additionally, it may be worth looking into [aeson-better-errors](https://hackage.haskell.org/package/aeson-better-errors), although I find its API somewhat strange compared to that of `aeson`.

**Comment by phadej** [comment]
`show v` is potentially a security bug, because `v` can be quite big. But I'll think about this.

**Comment by iphydf** [comment]
@taktoa do you know which PR is "blocked"?

**Comment by taktoa** [comment]
The "blocked" PR was the one you used in your example. Weirdly, I wouldn't get `"mergeable_state": "blocked"` when I open it in Chrome / with `curl`, but I did when doing the request through `github` (the Haskell library, that is).
