### ISSUE TITLE
Add support for releases

### ISSUE THREAD

**Issue by matthew-piziak** [phadej/github#270]
I am happy to help implement this, but there are pull requests in the queue that are several weeks old. The last commit was over a month ago. Is this library actively maintained?

**Comment by phadej** [comment]
It is, with some definition of "active"; there is no SLA, I might answer in 15 minutes, or I might be  busy with something else for few weeks... (Also I often miss PR updates, so friendly reminders are more then welcome, thanks for that).

**Comment by matthew-piziak** [comment]
Sounds good! I'll look into adding this functionality, then.

**Comment by matthew-piziak** [comment]
I've deprioritized this need so I won't be adding this in the near future. I'll stay subscribed to this issue though.
