### ISSUE TITLE
Release a new version with #271 in it.

### ISSUE THREAD

**Issue by iphydf** [phadej/github#276]
The github package has been broken for several months now. It is completely unusable for operating on pull requests until PR #271 is released.

**Comment by phadej** [comment]
Does `master` however works for you?

**Comment by phadej** [comment]
The next release would have GHC-8.2.1 support. I'm waiting dependencies to catch up. E.g. https://github.com/Soostone/uri-bytestring/pull/38

**Comment by iphydf** [comment]
@robinlinden can you test whether our tools and the webservice work with master?

**Comment by robinlinden** [comment]
Sorry, didn't notice I was tagged in this. It works with that PR in. This can be closed.

**Comment by iphydf** [comment]
It used to work, but now it no longer works, because while #271 adds "blocked", by now there is yet another one "behind", which was added after this release.

**Comment by iphydf** [comment]
(So yes, it works with master)

**Comment by phadej** [comment]
I'll have next release next week. Finally get to work on our Github integrations, so I'll need the release myself too. Thanks for all your patience.

**Comment by phadej** [comment]
https://hackage.haskell.org/package/github-0.19 done.

**Comment by iphydf** [comment]
Awesome!
