### ISSUE TITLE
pullRequest' returns a Parse Error

### ISSUE THREAD

**Issue by nicaudinet** [phadej/github#278]
Hi,

I've been trying to use the GitHub API to get the SHA of the head commit for every pull request in a repo. However, the function pullRequest' has a run-time error which returns:

> ParseError "Error in $['mergeable_state']: expected MergeableState, encountered String"

When I create my own request using pullRequestR and run it with executeRequestWithMgr, I get the same error. I have not managed to find a solution. Could this be a bug?

Thanks

**Comment by phadej** [comment]
Can you try with a master branch version, iirc something like that is fixed, and I'm soon (this week) making a release

**Comment by nicaudinet** [comment]
Hi!

I have indeed tried it with the most recent version, and it works as expected.

Thank you very much!
