### ISSUE TITLE
Function for forking an existing repo

### ISSUE THREAD

**Issue by erikd** [phadej/github#280]
Apparently the API for this [already exists](https://developer.github.com/v3/repos/forks/#create-a-fork) which would get turned into something like:
```
forkExistingRepoR :: RepoRef -> Request 'RW Repo
```

I'm willing to do the work implementing this. I just need some feedback on whether this seems to make sense.

**Comment by erikd** [comment]
@phadej ?

**Comment by phadej** [comment]
Sorry. PR would be great!

I'd prefer spelling out the three parameters `Name Owner -> Name Repo -> Maybe (Name Owner) -> Request 'RW Repo`

**Comment by erikd** [comment]
@phadej Sorry, what is the third parameter? The `Maybe (Name Owner)` ?

I was thinking of:
```
forkExistingRepo' :: Name Owner -> Name Repo -> Request 'RW Repo
```
where the first parameter is the owner of the repo that is being forked and the second parameter is the name of repo. Can't figure why there would be another parameter.

**Comment by phadej** [comment]
> Optional parameter to specify the organization name if forking into an organization.
