### ISSUE TITLE
Looking for Path (free category)?

### ISSUE THREAD

**Issue by ggreif** [phadej/github#283]
There is the `thrist` package on Hackage.

Sorry, but twitter won't let me answer your tweet :-(

   Gabor

**Comment by ggreif** [comment]
I see you got it :-)

**Comment by phadej** [comment]
@ggreif I also sent you an email about some improvement suggestions about the `thrist`, let's make the package even better!

**Comment by phadej** [comment]
... I hope it didn't go to spam, iki.fi mails tend to end there :/
