### ISSUE TITLE
Error in $.head.repo: expected Repo, encountered Null

### ISSUE THREAD

**Issue by iphydf** [phadej/github#310]
pullRequestCommitRepo can be null when a repo was deleted after a PR was created.

**Comment by iphydf** [comment]
`$ curl https://api.github.com/repos/TokTok/c-toxcore/pulls/519`

**Comment by iphydf** [comment]
https://gist.github.com/iphydf/4843ca31eab266496c4284bd9bcedfe8

**Comment by phadej** [comment]
Can you change the field to `Maybe` field? (no need to change `.:` to `.:?`)
