### ISSUE TITLE
Add notifications endpoints

### ISSUE THREAD

**Issue by IvanMalison** [phadej/github#323]
Looks like support for these endpoints hasn't been added yet.

I'm happy to contribute it, but I figured I'd file this issue
a) to indicate my intent
b) in case I don't end up following through

**Comment by IvanMalison** [comment]
@phadej Thanks for merging! Any chance you will cut a release soon?

**Comment by phadej** [comment]
@IvanMalison yes. The Travis-CI is current bottleneck, after the current top two PRs are merged, and some smoke testing is done, I'll cut a release.

~Tomorrow.
