### ISSUE TITLE
Allow auth using clientId and clientSecret

### ISSUE THREAD

**Issue by adetokunbo** [phadej/github#331]
The GitHub v3 API allows authentication using [clientId and clientSecret](https://developer.github.com/v3/#oauth2-keysecret), for use in server to server applications.

Would it be alright to add support for this in [Auth.hs](https://github.com/phadej/github/blob/master/src/GitHub/Auth.hs) and [Request.hs](https://github.com/phadej/github/blob/master/src/GitHub/Request.hs) ?

**Comment by phadej** [comment]
I think https://github.com/phadej/github/pull/365 "fixes" this. Please reopen / comment if I missed something.
