### ISSUE TITLE
organizationsR: ParseError "Error in $: expected Vector a, encountered Object"

### ISSUE THREAD

**Issue by domenkozar** [phadej/github#352]
```haskell
GitHub.organizationsR GitHub.FetchAll
```

Failed with `ParseError "Error in $: expected Vector a, encountered Object"`, but I'm unable to reproduce consistently. Will dig further.

**Comment by domenkozar** [comment]
Happens if the token doesn't have orgs scope.

**Comment by phadej** [comment]
Would be interesting to see the `Object` returned?

**Comment by phadej** [comment]
At least docs don't mention the `Object` in https://developer.github.com/v3/orgs/#list-your-organizations (but do mention scopes!)

Maybe I broke error-code handling in `0.21` ?

**Comment by domenkozar** [comment]
Most probably, I'd be highly surprised it returns 200.

**Comment by domenkozar** [comment]
About the `Object` contents, first need to make `Error` sum include the response content.

**Comment by domenkozar** [comment]
Quick review hints that `setCheckStatus` is gone now https://github.com/phadej/github/commit/c0e4ad33811be82e1f72ee76116345c681703103#diff-43f3bed87bf8280f89734d516127120bL228

**Comment by phadej** [comment]
Fixed by #354
