### ISSUE TITLE
Trying to create existing repo fails with ParseError

### ISSUE THREAD

**Issue by v0d1ch** [phadej/github#376]
I noticed that when trying to call `createOrganizationRepo'` for the repo that already exists I get 
```ParseError "Error in $: key "description" not present```

Description field for the repo is provided together with the rest of the needed data so this error is misleading. I can provide more details if it is hard to pinpoint why this fails.

**Comment by phadej** [comment]
Might be a duplicate of https://github.com/phadej/github/issues/352 as current `0.21` version fails to check error codes.
