### ISSUE TITLE
deleteComment: "Error in $: not enough input"

### ISSUE THREAD

**Issue by pbrisbin** [phadej/github#377]
### Repro

Save to `./gh-repro.hs`

```hs
{-# LANGUAGE OverloadedStrings #-}
module Main (main) where

import qualified Data.ByteString.Char8 as C8
import GitHub.Endpoints.Issues.Comments
import System.Environment (getEnv)

main :: IO ()
main = do
    let owner = "restyled-io"
        repo = "restyled.io"
        issue = IssueNumber 155
    auth <- OAuth . C8.pack <$> getEnv "GITHUB_ACCESS_TOKEN"
    Right comment <- createComment auth owner repo issue "Test comment"

    result <- deleteComment auth owner repo $ commentId comment

    print result

```

```console
GITHUB_ACCESS_TOKEN=<something with repo scopes> \
  stack runghc --resolver lts-13.23 --package github-0.21 ./gh-repro.hs
```

### Expected

The comment is removed and the API response successfully returned according to `deleteCommentR`'s type as:

```
Right ()
```

### Actual

The comment is removed, but the result is an error in `Left`:

```console
Left (ParseError "Error in $: not enough input")
```

### Hypothesis

The commonly-used `Request` synonym fixes [to `MtJSON`](https://hackage.haskell.org/package/github-0.21/docs/GitHub-Data-Request.html#t:Request), but [an endpoint such as this](https://developer.github.com/v3/issues/comments/#delete-a-comment) returns `204 No Content`, so trying to parse no content to `()` fails. I'm guessing such an endpoint function needs to use `MtUnit`.

**Comment by phadej** [comment]
Changing media-type to `MtUnit` might fix this.

Please try, and if it works, make a PR!

**Comment by phadej** [comment]
Hopefully fixed in https://github.com/phadej/github/commit/0247582839ce23b22acdc07bb1a52b6dc98c9a39

**Comment by pbrisbin** [comment]
Thank you for the quick fix!
