### ISSUE TITLE
URI escape segments before sending them to github

### ISSUE THREAD

**Issue by domenkozar** [phadej/github#398]
`GitHub.userInfoForR "bors[bot]"` fails as it needs to be URI escaped.

**Comment by phadej** [comment]
GitHub is missleading, have you tried that api really wants bors[bot] not just bors https://github.com/bors?

Also

**Comment by domenkozar** [comment]
This is somewhat a github apps feature, but the bot version returns different result: https://api.github.com/users/bors[bot]
