### ISSUE TITLE
Add support for label description field

### ISSUE THREAD

**Issue by maticzav** [phadej/github#400]
Hi 👋,

Firstly, thank you for creating this beautiful package. I am creating a Github App that heavily relies on `labels`, and would need access to the description field of labels in the repository. Would it be possible that you add support for that? If you'd guide me, I could also create a PR. 

Running through the source code, I believe these are the files that'd need to be changed:
- https://github.com/phadej/github/blob/master/src/GitHub/Endpoints/Issues/Labels.hs
- https://github.com/phadej/github/blob/master/src/GitHub/Data/Definitions.hs#L262

> https://developer.github.com/v3/issues/labels/#create-a-label for the reference

**Comment by phadej** [comment]
Thank you for your kind words.

PR are always welcome.

**Comment by sajidanower23** [comment]
@maticzav If you haven't started working on it, I am happy to look into it this week :)

**Comment by sajidanower23** [comment]
@maticzav It appears that @phadej is on a break. If it's urgent you can use #418 for the moment :+1:
