### ISSUE TITLE
GraphQL API v4

### ISSUE THREAD

**Issue by sshine** [phadej/github#406]
It says in the package synopsis that the package supports v3 of the API.

What are the implications of supporting v4 of the API?

https://developer.github.com/v4/

In particular, I am interested in the [`transferIssue`](https://developer.github.com/v4/mutation/transferissue/) endpoint.

**Comment by phadej** [comment]
GraphQL API v4 is not supported, and there are no plans to support it: GraphQL is so different than REST, that one don’t even benefit from REST type definitions.

**Comment by sshine** [comment]
I appreciate the insight! Thanks.
