### ISSUE TITLE
Support for querying repositories by identifier instead of owner/name

### ISSUE THREAD

**Issue by 3noch** [phadej/github#408]
Identifiers remain the same even if a repository's name gets changed or is moved to a new owner.

For example: https://api.github.com/repositories/20633049/contributors

**Comment by phadej** [comment]
Is that functionality documented on https://developer.github.com/v3 somewhere, if so PR is welcome.

**Comment by phadej** [comment]
Sorry, not good enough for me.

All the building blocks for making that endpoint yourself are there though, you don’t need to modify `github` to use it.

**Comment by 3noch** [comment]
Ok
