### ISSUE TITLE
replace cryptohash-sha1 and bytestring-base16 with cryptonite

### ISSUE THREAD

**Issue by domenkozar** [phadej/github#411]
cryptohash is deprecated (not really ideally for a security library) and it would get rid of one dependency.

**Comment by phadej** [comment]
cryptohash-sha1 is not cryptohash, and definitely not deprecated.

**Comment by domenkozar** [comment]
bytestring-base16 could still be replaced with memory, since memory is already in the transitive dependency tree.

cryptohash-* accumulate application dependency tree as they almost always duplicate with cryptonite package, so trading one package for another seems little to gain compared to the result in real-world haskell application.

**Comment by phadej** [comment]
If you look properly, `memory` is not in the dependency tree with default flags.

![deps](https://user-images.githubusercontent.com/51087/68666625-ecfedb00-054c-11ea-8dbc-d4ae03d00b34.png)

I prefer `openssl` over `cryptonite`, and IMHO you should to.

**Comment by domenkozar** [comment]
It is there, just above semigroups.

> I prefer openssl over cryptonite, and IMHO you should to.

I would, but cryptohash-sha1 doesn't seem to use openssl.

**Comment by phadej** [comment]
Sad, `http-client` used not to depend on `memory`. I cannot help that.
