### ISSUE TITLE
Edit issue should work with IssueNumber instead of `Id Issue`

### ISSUE THREAD

**Issue by vrom911** [phadej/github#428]
As per the [specifications](https://developer.github.com/v3/issues/#edit-an-issue), the endpoint should contain the issue number, not the issue ID.

Currently, `editIssueR` has the following type:

```haskell
editIssueR :: Name Owner -> Name Repo -> Id Issue -> EditIssue -> Request 'RW Issue
```

I propose to change it to:

```haskell
editIssueR :: Name Owner -> Name Repo -> IssueNumber -> EditIssue -> Request 'RW Issue
```

**Comment by phadej** [comment]
Thanks for catching this. PR would be nice.
