### ISSUE TITLE
Build error with GHC 8.10.1

### ISSUE THREAD

**Issue by asr** [phadej/github#435]
I cannot install the library with GHC 8.10.1 because i) the upper bound version for `base` and ii) https://github.com/haskell-hvr/deepseq-generics/issues/8.  

Blocking https://github.com/agda/agda/issues/4582.

**Comment by asr** [comment]
Issue https://github.com/haskell-hvr/deepseq-generics/issues/8 was fixed.

**Comment by asr** [comment]
Any news?

**Comment by asr** [comment]
Any news?

**Comment by phadej** [comment]
Released https://hackage.haskell.org/package/github-0.26
