### ISSUE TITLE
the very first example does not work

### ISSUE THREAD

**Issue by lclem** [phadej/github#440]
I run the readme example below
and it says "Module ‘GitHub’ does not export ‘github'’"

```haskell
{-# LANGUAGE NoImplicitPrelude #-}
{-# LANGUAGE OverloadedStrings #-}

import Prelude.Compat

import Data.Text         (Text, pack)
import Data.Text.IO as T (putStrLn)
import Data.Monoid       ((<>))

import GitHub (github')
import qualified GitHub

main :: IO ()
main = do
    possibleUsers <- github' GitHub.usersFollowingR "phadej"
    T.putStrLn $ either (("Error: " <>) . pack . show)
                        (foldMap ((<> "\n") . formatUser))
                        possibleUsers

formatUser :: GitHub.SimpleUser -> Text
formatUser = GitHub.untagName . GitHub.simpleUserLogin
```

It would be great to have working examples for this API :)

**Comment by phadej** [comment]
Which version of `github` you are using, and which documentation you are looking at.

With `github-0.25`:

```
GHCi, version 8.8.3: https://www.haskell.org/ghc/  :? for help
Loaded package environment from /home/ogre/.ghc/x86_64-linux-8.8.3/environments/default
Loaded GHCi configuration from /home/ogre/.ghci
Prelude> :m +GitHub
Prelude GitHub> :t github'
github' :: GitHubRO req res => req -> res
```

**Comment by lclem** [comment]
I'm using stack and it insists on using `github-0.16.0`, that's why...
I put `- github >= 0.25` in the `dependencies:` section of my `package.yaml` file, but when I run `stack run` it says

`github-0.16.0 from stack configuration does not match >=0.25  (latest matching version is 0.25)`

any hint how to fix this? (I'm aware it is not longer a haskell github api issue.)

**Comment by phadej** [comment]
IIRC you have either to add newer versions to `extra-deps` or upgrade your resolver to one which includes `github-0.25` (or to look at `github-0.16` documentation).

I'm not a stack user myself, so please refer to their documentation for more.

**Comment by lclem** [comment]
many thanks!
