### ISSUE TITLE
Where is version 0.25?

### ISSUE THREAD

**Issue by srid** [phadej/github#442]
`master`'s CHANGELOG.md and .cabal file both indicate that the latest version is 0.24. Yet Hackage has version 0.25 with its [changelog](https://hackage.haskell.org/package/github-0.25/changelog) showing a bunch of changes in 0.25. 

I don't see this version on Github. @phadej

**Comment by phadej** [comment]
I guess I forgot to push. Yet, unfortunately I don't have access to the machine for the next week or so.

**Comment by phadej** [comment]
Pushed the branch with that commit.
