### ISSUE TITLE
DNS errors cause IO exceptions

### ISSUE THREAD

**Issue by TomMD** [phadej/github#443]
Consider:

    github (EnterpriseOAuth "https://not.a.real.domain" "thisToken") $ repositoryR "user" "repo"

Or more meaningfully, consider what happened just now - https://api.github.com didn't resolve.

Both situations cause an IO exception.  Seeing as `github` is already returning an Either should we catch synchronous exceptions like this and place them in `GitHub.Data.Definitions.Error`?

As an alternative we could limit the catch to only `ConnectionFailure` and `InvalidUrlException`, but then someone else will probably stumble across the same issue with another exception to add to the list.

**Comment by phadej** [comment]
Idn't InvalidUrlException catched as part of `HTTPError`, ditto `ConnectionFailure`?

If they aren't, it's a bug.

**Comment by TomMD** [comment]
Hurm, yes my example does return a `Left foo` and not an IO exception.  It seems I must be more careful and find what specific exception was actually occurring here.
