### ISSUE TITLE
Information returned by call to Github.Gists.gist not interpreted correctly

### ISSUE THREAD

**Issue by tittoassini** [phadej/github#59]
import qualified Github.Gists as Github
main =  Github.gist "23084"

returns:

Left (JsonError "Could not build a GithubOwner out of Null on the JSON: ...

Apparently the user information returned by github has changed.

The problem is in:
module Github.Data where
....
instance FromJSON GithubOwner where
 ....

**Comment by jwiegley** [comment]
@tittoassini Is this still an issue?
