### ISSUE TITLE
Information-free types

### ISSUE THREAD

**Issue by bitemyapp** [phadej/github#84]
```
Prelude> :t Github.commitCommentsFor
Github.commitCommentsFor
  :: String -> String -> String -> IO (Either Github.Error [Github.Comment])
```

At minimum, these should be type aliases but that still permits the possibility of transposition errors and makes consumption of the API in-place still unclear. Ideally, all the Stringly nonsense should be placed with newtypes.

An example from Bloodhound:

```haskell
posQuery = QueryMatchQuery $ mkMatchQuery (FieldName "user") (QueryString "bitemyapp")
```

I don't have to guess what "user" and "bitemyapp" are - the code tells me.

**Comment by phadej** [comment]
:+1:
Even this would be breaking change

**Comment by jwiegley** [comment]
Note that this can also be quite annoying if taken too far. It should be used in places where ambiguity is likely and highly problematic; I'm not convinced it should be done everywhere that is possible.

**Comment by bitemyapp** [comment]
>I'm not convinced it should be done everywhere that is possible.

Quite possible I don't feel this pain as much because I usually have [iso](http://hackage.haskell.org/package/lens-4.13/docs/Control-Lens-Iso.html#v:iso), [ala](http://hackage.haskell.org/package/newtype-0.2/docs/Control-Newtype.html#v:ala) or [coerce](http://hackage.haskell.org/package/base-4.8.1.0/docs/Data-Coerce.html#v:coerce) in scope.

**Comment by phadej** [comment]
Something is already done in http://hackage.haskell.org/package/github-0.14.0/candidate
Let's make more changes on need

**Comment by bitemyapp** [comment]
@phadej what is it you believe disposed of this issue?

**Comment by phadej** [comment]
@bitemyapp unfortunately I don't fully know what you'd like to see for this issue. There are no plan, and something is already done.

If you really like to see something happen, please make a concrete proposal to be implemented. All endpoint (and their parameters) are visible at http://hackage.haskell.org/package/github-0.14.0/candidate/docs/Github-All.html. The *better* function type signatures would be a good conversation starter.

**Comment by bitemyapp** [comment]
@phadej it's not to my usual preference, but this does seem to be a reasonable attempt at solving the discoverability/new user experience issues for the documentation.

![screenshot from 2016-01-11 14-37-19](https://cloud.githubusercontent.com/assets/320177/12245880/e86599da-b870-11e5-8be9-d689541049aa.png)

Accordingly I'll stop agitating for now and see if anybody complains about the implementation.

Thank you for picking up the library :smile:
