### ISSUE TITLE
I can't tell what Github API endpoints this library supports

### ISSUE THREAD

**Issue by bitemyapp** [phadej/github#85]
Spent over an hour looking through the source and Hackage, still not sure if it supports Notifications and Events.

Does this library support every endpoint? If so, please say so.

If not, please say what it does or does not support.

**Comment by jwiegley** [comment]
It supports whatever endpoints its contributors have needed, thus far.  There is no commitment to completeness, as I don't think there's anyone who'd be willing to support it.

**Comment by bitemyapp** [comment]
@jwiegley point was more about documentation, than completeness. Could we leave this open for anybody who might want a documentation ticket to chomp into?

**Comment by jwiegley** [comment]
I whole-heartedly welcome documentation on the APIs we do support, and perhaps mention of what we don't (although that list is likely to change without notice).  I guess we could have put restrictions on accepting PRs without documentation, but that ship has sailed...

**Comment by phadej** [comment]
I'll create a `Github.All` module while going thru what is implemented https://github.com/phadej/github/pull/139

<img width="750" alt="screen shot 2016-01-03 at 19 20 08" src="https://cloud.githubusercontent.com/assets/51087/12079796/0f66232e-b24f-11e5-96fe-f6496bbd93d9.png">

**Comment by phadej** [comment]
http://hackage.haskell.org/package/github-0.14.0/candidate
